<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acenta extends CI_Controller{
    function __construct()
    {
        parent::__construct();

	
        $this->load->model('Acenta_model');
		$this->load->model('Ogrenci_model');
		$this->zaman = date('Y-m-d H:i:s');
    } 

    /*
     * Listing of acenta
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('acenta/index?');
        $config['total_rows'] = $this->Acenta_model->get_all_acenta_count();
        $this->pagination->initialize($config);

        $data['acenta'] = $this->Acenta_model->get_all_acenta($params);

        $data['_view'] = 'acenta/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new acenta
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('adi','Agent Name','required');
		$this->form_validation->set_rules('ulke','Country','required');
		$this->form_validation->set_rules('mail','Email','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ulke' => $this->input->post('ulke'),
				'durum' => $this->input->post('durum'),
			
				'adi' => $this->input->post('adi'),
				'mail' => $this->input->post('mail'),
				'sehir' => $this->input->post('sehir'),
				'tel1' => $this->input->post('tel1'),
				'tel2' => $this->input->post('tel2'),
				'aciklama' => $this->input->post('aciklama'),
				'zaman' => $this->zaman,
            );
            
            $acenta_id = $this->Acenta_model->add_acenta($params);
            redirect('acenta/index');
        }
        else
        {
			$this->load->model('Ulkeler_model');
			$data['all_ulkeler'] = $this->Ulkeler_model->get_all_ulkeler();

			$this->load->model('Durumlar_model');
			$data['all_durumlar'] = $this->Durumlar_model->get_all_durumlar();
            
            $data['_view'] = 'acenta/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a acenta
     */
    function edit($acenta_id)
    {   
        // check if the acenta exists before trying to edit it
        $data['acenta'] = $this->Acenta_model->get_acenta($acenta_id);
        
        if(isset($data['acenta']['acenta_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('adi','Adi','required');
			$this->form_validation->set_rules('ulke','Ulke','required');
			$this->form_validation->set_rules('mail','Email','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ulke' => $this->input->post('ulke'),
					'durum' => $this->input->post('durum'),
					
					'adi' => $this->input->post('adi'),
					'mail' => $this->input->post('mail'),
					'sehir' => $this->input->post('sehir'),
					'tel1' => $this->input->post('tel1'),
					'tel2' => $this->input->post('tel2'),
					'aciklama' => $this->input->post('aciklama'),
                );

                $this->Acenta_model->update_acenta($acenta_id,$params);            
                redirect('acenta/index');
            }
            else
            {
				$this->load->model('Ulkeler_model');
				$data['all_ulkeler'] = $this->Ulkeler_model->get_all_ulkeler();

				$this->load->model('Durumlar_model');
				$data['all_durumlar'] = $this->Durumlar_model->get_all_durumlar();

                $data['_view'] = 'acenta/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Agent you are trying to edit does not exist.');
    }
}
