<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Basvuru_surec extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Basvuru_surec_model');
		$zaman = date('Y-m-d H:i:s');
    }

    /*
     * Adding a new basvuru_surec
     */
    function add()
    {  
	
        if(isset($_POST) && count($_POST) > 0)     
        {   if($this->input->post('islem') == '') {
			redirect('basvuru_surec/add');
				}	
            $params = array(
				'o_id' => $this->input->post('o_id'),
				'islem' => $this->input->post('islem'),
				'zaman' => $zaman,
            );
            
            $basvuru_surec_id = $this->Basvuru_surec_model->add_basvuru_surec($params);
            redirect('basvuru_surec/add');
        }
        else
        {
			$this->load->model('Ogrenci_model');
			$data['all_ogrenci'] = $this->Ogrenci_model->get_all_ogrenci();
            
            $data['_view'] = 'basvuru_surec/add';
            $this->load->view('layouts/main',$data);
        }
    }
	
}
