<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bolum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bolum_model');
		$this->yetki = $this->session->userdata('yetki');
		//if($this->yetki<3) { } else { 		show_error('Yönetici iznine sahip olmanız gerekmektedir.');			}
    } 

    /*
     * Listing of bolum
     */
    function index()
    {
		if($this->yetki<3) {

		$params['arsiv'] = $this->input->get('arsiv');
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('bolum/index?');
        $config['total_rows'] = $this->Bolum_model->get_all_bolum_count();
        $this->pagination->initialize($config);

        $data['bolum'] = $this->Bolum_model->get_all_bolum($params);
        
        $data['_view'] = 'bolum/index';
        $this->load->view('layouts/main',$data);
		} else { 		show_error('You must have administrator permission.');			}
    }

    /*
     * Adding a new bolum
     */
    function add()
    { 
	if($this->yetki<3) {	
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'f_id' => $this->input->post('f_id'),
				'bolum_durum' => $this->input->post('bolum_durum'),
				'bolum_adi' => $this->input->post('bolum_adi'),
				'egitim_sure' => $this->input->post('egitim_sure'),
				'egitim_dili' => $this->input->post('egitim_dili'),
				'aciklama' => $this->input->post('aciklama'),
				'ucreti' => $this->input->post('ucreti'),
            );
            
            $bolum_id = $this->Bolum_model->add_bolum($params);
            redirect('bolum/index');
        }
        else
        {
			$this->load->model('Fakulte_model');
			$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

			$this->load->model('Bolum_durumlari_model');
			$data['all_bolum_durumlari'] = $this->Bolum_durumlari_model->get_all_bolum_durumlari();
            
            $data['_view'] = 'bolum/add';
            $this->load->view('layouts/main',$data);
        }
	} else { 		show_error('You must have administrator permission.');			}
    }  

    /*
     * Editing a bolum
     */
    function edit($bolum_id)
    { 
	if($this->yetki<3) {	
        // check if the bolum exists before trying to edit it
        $data['bolum'] = $this->Bolum_model->get_bolum($bolum_id);
        
        if(isset($data['bolum']['bolum_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'f_id' => $this->input->post('f_id'),
					'bolum_durum' => $this->input->post('bolum_durum'),
					'bolum_adi' => $this->input->post('bolum_adi'),
					'egitim_sure' => $this->input->post('egitim_sure'),
					'egitim_dili' => $this->input->post('egitim_dili'),
					'aciklama' => $this->input->post('aciklama'),
					'ucreti' => $this->input->post('ucreti'),
					
                );

                $this->Bolum_model->update_bolum($bolum_id,$params);            
                redirect('bolum/index');
            }
            else
            {
				$this->load->model('Fakulte_model');
				$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

				$this->load->model('Bolum_durumlari_model');
				$data['all_bolum_durumlari'] = $this->Bolum_durumlari_model->get_all_bolum_durumlari();

                $data['_view'] = 'bolum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Program you are trying to edit does not exist.');
	} else { 		show_error('You must have administrator permission.');			}
    } 

	
	    /*
     * Editing a katalog_detay
     */
    function katalog_detay($bolum_id)
    {   
        // check if the bolum exists before trying to edit it
        $data['bolum'] = $this->Bolum_model->get_bolum($bolum_id);
        

          
				$this->load->model('Fakulte_model');
				$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

				$this->load->model('Bolum_durumlari_model');
				$data['all_bolum_durumlari'] = $this->Bolum_durumlari_model->get_all_bolum_durumlari();

                $data['_view'] = 'bolum/katalog_detay';
                $this->load->view('layouts/main',$data);
            

    } 

	
    /*
     * Deleting bolum
     */
    function remove($bolum_id)
    {
		if($this->yetki<3) {
        $bolum = $this->Bolum_model->get_bolum($bolum_id);

        // check if the bolum exists before trying to delete it
        if(isset($bolum['bolum_id']))
        {
            $this->Bolum_model->delete_bolum($bolum_id);
            redirect('bolum/index');
        }
        else
            show_error('The Program you are trying to delete does not exist.');
		} else { 		show_error('You must have administrator permission.');			}
    }
						
    
}
