<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bolum_durumlari extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bolum_durumlari_model');
				$this->yetki = $this->session->userdata('yetki');
		if($this->yetki<3) { } else { 		show_error('You must have administrator permission.');			}
    } 

    /*
     * Listing of bolum_durumlari
     */
    function index()
    {
        $data['bolum_durumlari'] = $this->Bolum_durumlari_model->get_all_bolum_durumlari();
        
        $data['_view'] = 'bolum_durumlari/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bolum_durumlari
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'bolum_durum_adi' => $this->input->post('bolum_durum_adi'),
            );
            
            $bolum_durumlari_id = $this->Bolum_durumlari_model->add_bolum_durumlari($params);
            redirect('bolum_durumlari/index');
        }
        else
        {            
            $data['_view'] = 'bolum_durumlari/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bolum_durumlari
     */
    function edit($bolum_durumlari_id)
    {   
        // check if the bolum_durumlari exists before trying to edit it
        $data['bolum_durumlari'] = $this->Bolum_durumlari_model->get_bolum_durumlari($bolum_durumlari_id);
        
        if(isset($data['bolum_durumlari']['bolum_durumlari_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'bolum_durum_adi' => $this->input->post('bolum_durum_adi'),
                );

                $this->Bolum_durumlari_model->update_bolum_durumlari($bolum_durumlari_id,$params);            
                redirect('bolum_durumlari/index');
            }
            else
            {
                $data['_view'] = 'bolum_durumlari/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Program Status you are trying to edit does not exist.');
    } 

    /*
     * Deleting bolum_durumlari
     */
    function remove($bolum_durumlari_id)
    {
        $bolum_durumlari = $this->Bolum_durumlari_model->get_bolum_durumlari($bolum_durumlari_id);

        // check if the bolum_durumlari exists before trying to delete it
        if(isset($bolum_durumlari['bolum_durumlari_id']))
        {
            $this->Bolum_durumlari_model->delete_bolum_durumlari($bolum_durumlari_id);
            redirect('bolum_durumlari/index');
        }
        else
            show_error('The Program Status you are trying to delete does not exist.');
    }
    
}
