<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$this->y_okul_id = $this->session->userdata('y_okul_id');
        
    }

    function index()
    {
		
		/* toplam öğrenci sayısı */
		$this->db->from('ogrenci');
	//	$y_okul_id = $this->session->userdata('y_okul_id');
		if($this->y_okul_id != 0) { $this->db->where('a_id' , $this->y_okul_id);}
        $data['ogrenci_sayisi'] = $this->db->count_all_results();
		/* bitiş */
				/* işlemde alan öğrenci sayısı */
		$this->db->from('ogrenci');
	//	$y_okul_id = $this->session->userdata('y_okul_id');
		if($this->y_okul_id != 0) { $this->db->where('a_id' , $this->y_okul_id);}
		$this->db->where('durum', '2');
        $data['ogrenci_sayisi_islemde'] = $this->db->count_all_results();
		/* bitiş */

				/* kabul alan öğrenci sayısı */
		$this->db->from('ogrenci');
	//	$y_okul_id = $this->session->userdata('y_okul_id');
		if($this->y_okul_id != 0) { $this->db->where('a_id' , $this->y_okul_id);}
		$this->db->where('durum', '3');
        $data['ogrenci_sayisi_kabul'] = $this->db->count_all_results();
		/* bitiş */
		
		/* acenta ile ilgli son işlemler */	;
		if($this->y_okul_id != 0) { 
		$query = $this->db->query('SELECT * FROM basvuru_surec where a_id="'.$this->y_okul_id.'" order by surec_id desc limit 0,10');
		} else {
		$query = $this->db->query('SELECT * FROM basvuru_surec order by surec_id desc limit 0,10 ');
		}
		$data['surec'] = $query->result_array();
		
	//	
		/* bitiş */
		
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
		
    }
}
