<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Durumlar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Durumlar_model');
				$this->yetki = $this->session->userdata('yetki');
		if($this->yetki<3) { } else { 		show_error('You must have administrator permission.');			}
    } 

    /*
     * Listing of durumlar
     */
    function index()
    {
        $data['durumlar'] = $this->Durumlar_model->get_all_durumlar();
        
        $data['_view'] = 'durumlar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new durumlar
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'durum_adi' => $this->input->post('durum_adi'),
            );
            
            $durumlar_id = $this->Durumlar_model->add_durumlar($params);
            redirect('durumlar/index');
        }
        else
        {            
            $data['_view'] = 'durumlar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a durumlar
     */
    function edit($durum_id)
    {   
        // check if the durumlar exists before trying to edit it
        $data['durumlar'] = $this->Durumlar_model->get_durumlar($durum_id);
        
        if(isset($data['durumlar']['durum_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'durum_adi' => $this->input->post('durum_adi'),
                );

                $this->Durumlar_model->update_durumlar($durum_id,$params);            
                redirect('durumlar/index');
            }
            else
            {
                $data['_view'] = 'durumlar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Status you are trying to edit does not exist.');
    } 

    /*
     * Deleting durumlar
     */
    function remove($durum_id)
    {
        $durumlar = $this->Durumlar_model->get_durumlar($durum_id);

        // check if the durumlar exists before trying to delete it
        if(isset($durumlar['durum_id']))
        {
            $this->Durumlar_model->delete_durumlar($durum_id);
            redirect('durumlar/index');
        }
        else
            show_error('The Status you are trying to delete does not exist.');
    }
    
}
