<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Evraklar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Evraklar_model');
    } 

    /*
     * Listing of evraklar
     */
    function index()
    {
        $data['evraklar'] = $this->Evraklar_model->get_all_evraklar();
        
        $data['_view'] = 'evraklar/index';
        $this->load->view('layouts/main',$data);
    }
    /*
     * Listing of evraklar for ogrenci
     */
    function ogrenci_evrak($ogrenci_id)
    {
        $data['evraklar'] = $this->Evraklar_model->get_ogrenci_evraklar($ogrenci_id);
        
        $data['_view'] = 'evraklar/ogrenci_evrak';
        $this->load->view('layouts/main',$data);
    }
	
    /*
     * Adding a new evraklar
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'o_id' => $this->input->post('o_id'),
				'evrak1' => $this->input->post('evrak1'),
				'evrak2' => $this->input->post('evrak2'),
				'evrak3' => $this->input->post('evrak3'),
				'evrak4' => $this->input->post('evrak4'),
				'evrak5' => $this->input->post('evrak5'),
            );
            
            $evraklar_id = $this->Evraklar_model->add_evraklar($params);
            redirect('evraklar/index');
        }
        else
        {
			$this->load->model('Ogrenci_model');
			$data['all_ogrenci'] = $this->Ogrenci_model->get_all_ogrenci();
            
            $data['_view'] = 'evraklar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

   
    /*
     * Adding a new evraklar
     */
    function evrak_ekle($evrak_id)
    {   
        // check if the evraklar exists before trying to edit it
        $data['evraklar'] = $this->Evraklar_model->get_evraklar($evrak_id);
        
        if(isset($data['evraklar']['evrak_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					//'o_id' => $this->input->post('o_id'),
					'evrak1' => $this->input->post('evrak1'),
					'evrak2' => $this->input->post('evrak2'),
					'evrak3' => $this->input->post('evrak3'),
					'evrak4' => $this->input->post('evrak4'),
					'evrak5' => $this->input->post('evrak5'),
                );

                $this->Evraklar_model->update_evraklar($evrak_id,$params);            
                redirect('evraklar/evrak_ekle/'.$evrak_id);
            }
            else
            {
				$this->load->model('Ogrenci_model');
				$data['all_ogrenci'] = $this->Ogrenci_model->get_all_ogrenci();

                $data['_view'] = 'evraklar/evrak_ekle';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Documents you are trying to edit does not exist.');
    } 

 /*
     * Editing a evraklar
     */
    function edit($evrak_id)
    {   
        // check if the evraklar exists before trying to edit it
        $data['evraklar'] = $this->Evraklar_model->get_evraklar($evrak_id);
        
        if(isset($data['evraklar']['evrak_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'o_id' => $this->input->post('o_id'),
					'evrak1' => $this->input->post('evrak1'),
					'evrak2' => $this->input->post('evrak2'),
					'evrak3' => $this->input->post('evrak3'),
					'evrak4' => $this->input->post('evrak4'),
					'evrak5' => $this->input->post('evrak5'),
                );

                $this->Evraklar_model->update_evraklar($evrak_id,$params);            
                redirect('evraklar/index');
            }
            else
            {
				$this->load->model('Ogrenci_model');
				$data['all_ogrenci'] = $this->Ogrenci_model->get_all_ogrenci();

                $data['_view'] = 'evraklar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Documents you are trying to edit does not exist.');
    } 

    /*
     * Deleting evraklar
     */
    function remove($evrak_id)
    {
        $evraklar = $this->Evraklar_model->get_evraklar($evrak_id);

        // check if the evraklar exists before trying to delete it
        if(isset($evraklar['evrak_id']))
        {
            $this->Evraklar_model->delete_evraklar($evrak_id);
            redirect('evraklar/index');
        }
        else
            show_error('The Documents you are trying to delete does not exist.');
    }
    
}
