<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fakulte extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fakulte_model');
				$this->yetki = $this->session->userdata('yetki');
		if($this->yetki<3) { } else { 		show_error('You must have administrator permission.');			}
    } 

    /*
     * Listing of fakulte
     */
    function index()
    {
        $data['fakulte'] = $this->Fakulte_model->get_all_fakulte();
        
        $data['_view'] = 'fakulte/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fakulte
     */
    function add()
    {   
        $this->load->library('form_validation');
		$this->form_validation->set_rules('fakulte_adi','Faculty Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'fakulte_adi' => $this->input->post('fakulte_adi'),
				'seviye' => $this->input->post('seviye'),
            );
            
            $fakulte_id = $this->Fakulte_model->add_fakulte($params);
            redirect('fakulte/index');
        }
        else
        {            
            $data['_view'] = 'fakulte/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fakulte
     */
    function edit($fakulte_id)
    {   
        // check if the fakulte exists before trying to edit it
        $data['fakulte'] = $this->Fakulte_model->get_fakulte($fakulte_id);
        
        if(isset($data['fakulte']['fakulte_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('fakulte_adi','Faculty Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'fakulte_adi' => $this->input->post('fakulte_adi'),
					'seviye' => $this->input->post('seviye'),
                );

                $this->Fakulte_model->update_fakulte($fakulte_id,$params);            
                redirect('fakulte/index');
            }
            else
            {

						
                $data['_view'] = 'fakulte/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Faculty you are trying to edit does not exist.');
    } 

    /*
     * Deleting fakulte
     */
    function remove($fakulte_id)
    {
        $fakulte = $this->Fakulte_model->get_fakulte($fakulte_id);

        // check if the fakulte exists before trying to delete it
        if(isset($fakulte['fakulte_id']))
        {
            $this->Fakulte_model->delete_fakulte($fakulte_id);
            redirect('fakulte/index');
        }
        else
            show_error('The Faculty you are trying to delete does not exist.');
    }
    
}
