<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ogrenci_secimi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ogrenci_secimi_model');
    } 

    /*
     * Listing of ogrenci_secimi
     */
    function index()
    {
        $data['ogrenci_secimi'] = $this->Ogrenci_secimi_model->get_all_ogrenci_secimi();
        
        $data['_view'] = 'ogrenci_secimi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ogrenci_secimi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'o_id' => $this->input->post('o_id'),
				'f_id' => $this->input->post('f_id'),
				'b_id' => $this->input->post('b_id'),
            );
            
            $ogrenci_secimi_id = $this->Ogrenci_secimi_model->add_ogrenci_secimi($params);
            redirect('ogrenci_secimi/index');
        }
        else
        {
			$this->load->model('Ogrenci_model');
			$data['all_ogrenci'] = $this->Ogrenci_model->get_all_ogrenci();

			$this->load->model('Fakulte_model');
			$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

			$this->load->model('Programlar_model');
			$data['all_programlar'] = $this->Programlar_model->get_all_programlar();
            
            $data['_view'] = 'ogrenci_secimi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ogrenci_secimi
     */
    function edit($id)
    {   
        // check if the ogrenci_secimi exists before trying to edit it
        $data['ogrenci_secimi'] = $this->Ogrenci_secimi_model->get_ogrenci_secimi($id);
        
        if(isset($data['ogrenci_secimi']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'o_id' => $this->input->post('o_id'),
					'f_id' => $this->input->post('f_id'),
					'b_id' => $this->input->post('b_id'),
                );

                $this->Ogrenci_secimi_model->update_ogrenci_secimi($id,$params);            
                redirect('ogrenci_secimi/index');
            }
            else
            {
				$this->load->model('Ogrenci_model');
				$data['all_ogrenci'] = $this->Ogrenci_model->get_all_ogrenci();

				$this->load->model('Fakulte_model');
				$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

				$this->load->model('Programlar_model');
				$data['all_programlar'] = $this->Programlar_model->get_all_programlar();

                $data['_view'] = 'ogrenci_secimi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Student Selection you are trying to edit does not exist.');
    } 

    /*
     * Deleting ogrenci_secimi
     */
    function remove($id)
    {
        $ogrenci_secimi = $this->Ogrenci_secimi_model->get_ogrenci_secimi($id);

        // check if the ogrenci_secimi exists before trying to delete it
        if(isset($ogrenci_secimi['id']))
        {
            $this->Ogrenci_secimi_model->delete_ogrenci_secimi($id);
            redirect('ogrenci_secimi/index');
        }
        else
            show_error('The Student Selection you are trying to delete does not exist.');
    }
    
}
