<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programlar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Programlar_model');
    } 

    /*
     * Listing of programlar
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('programlar/index?');
        $config['total_rows'] = $this->Programlar_model->get_all_programlar_count();
        $this->pagination->initialize($config);

        $data['programlar'] = $this->Programlar_model->get_all_programlar($params);
        
        $data['_view'] = 'programlar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new programlar
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'durum' => $this->input->post('durum'),
				'fakulte' => $this->input->post('fakulte'),
				'bolum' => $this->input->post('bolum'),
				'adi' => $this->input->post('adi'),
				'fiyat' => $this->input->post('fiyat'),
				'egit_sure' => $this->input->post('egit_sure'),
				'egit_dili' => $this->input->post('egit_dili'),
				'aciklama' => $this->input->post('aciklama'),
            );
            
            $programlar_id = $this->Programlar_model->add_programlar($params);
            redirect('programlar/index');
        }
        else
        {
			$this->load->model('Durumlar_model');
			$data['all_durumlar'] = $this->Durumlar_model->get_all_durumlar();

			$this->load->model('Fakulte_model');
			$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

			$this->load->model('Bolum_model');
			$data['all_bolum'] = $this->Bolum_model->get_all_bolum();
            
            $data['_view'] = 'programlar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a programlar
     */
    function edit($program_id)
    {   
        // check if the programlar exists before trying to edit it
        $data['programlar'] = $this->Programlar_model->get_programlar($program_id);
        
        if(isset($data['programlar']['program_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'durum' => $this->input->post('durum'),
					'fakulte' => $this->input->post('fakulte'),
					'bolum' => $this->input->post('bolum'),
					'adi' => $this->input->post('adi'),
					'fiyat' => $this->input->post('fiyat'),
					'egit_sure' => $this->input->post('egit_sure'),
					'egit_dili' => $this->input->post('egit_dili'),
					'aciklama' => $this->input->post('aciklama'),
                );

                $this->Programlar_model->update_programlar($program_id,$params);            
                redirect('programlar/index');
            }
            else
            {
				$this->load->model('Durumlar_model');
				$data['all_durumlar'] = $this->Durumlar_model->get_all_durumlar();

				$this->load->model('Fakulte_model');
				$data['all_fakulte'] = $this->Fakulte_model->get_all_fakulte();

				$this->load->model('Bolum_model');
				$data['all_bolum'] = $this->Bolum_model->get_all_bolum();

                $data['_view'] = 'programlar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The program you are trying to edit does not exist.');
    } 

    /*
     * Deleting programlar
     */
    function remove($program_id)
    {
        $programlar = $this->Programlar_model->get_programlar($program_id);

        // check if the programlar exists before trying to delete it
        if(isset($programlar['program_id']))
        {
            $this->Programlar_model->delete_programlar($program_id);
            redirect('programlar/index');
        }
        else
            show_error('The program you are trying to delete does not exist.');
    }
    
}
