<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ulkeler extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ulkeler_model');
				$this->yetki = $this->session->userdata('yetki');
		if($this->yetki<3) { } else { 		show_error('You must have administrator permission.');			}
    } 

    /*
     * Listing of ulkeler
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('ulkeler/index?');
        $config['total_rows'] = $this->Ulkeler_model->get_all_ulkeler_count();
        $this->pagination->initialize($config);

        $data['ulkeler'] = $this->Ulkeler_model->get_all_ulkeler($params);
        
        $data['_view'] = 'ulkeler/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ulkeler
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('ulke_adi','Country Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ulke_adi' => $this->input->post('ulke_adi'),
            );
            
            $ulkeler_id = $this->Ulkeler_model->add_ulkeler($params);
            redirect('ulkeler/index');
        }
        else
        {            
            $data['_view'] = 'ulkeler/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ulkeler
     */
    function edit($ulke_id)
    {   
        // check if the ulkeler exists before trying to edit it
        $data['ulkeler'] = $this->Ulkeler_model->get_ulkeler($ulke_id);
        
        if(isset($data['ulkeler']['ulke_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('ulke_adi','Country Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ulke_adi' => $this->input->post('ulke_adi'),
                );

                $this->Ulkeler_model->update_ulkeler($ulke_id,$params);            
                redirect('ulkeler/index');
            }
            else
            {
                $data['_view'] = 'ulkeler/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Country you are trying to edit does not exist.');
    } 

    /*
     * Deleting ulkeler
     */
    function remove($ulke_id)
    {
        $ulkeler = $this->Ulkeler_model->get_ulkeler($ulke_id);

        // check if the ulkeler exists before trying to delete it
        if(isset($ulkeler['ulke_id']))
        {
            $this->Ulkeler_model->delete_ulkeler($ulke_id);
            redirect('ulkeler/index');
        }
        else
            show_error('The Country you are trying to delete does not exist.');
    }
    
}
