<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Yonetici extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Yonetici_model');
        $this->yetki = $this->session->userdata('yetki');
    }

    /*
     * Listing of yonetici
     */
    function index()
    {
        if ($this->yetki < 3) {
            $params['limit'] = RECORDS_PER_PAGE;
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('yonetici/index?');
            $config['total_rows'] = $this->Yonetici_model->get_all_yonetici_count();
            $this->pagination->initialize($config);

            $data['yonetici'] = $this->Yonetici_model->get_all_yonetici($params);
            $data['_view'] = 'yonetici/index';
            $this->load->view('layouts/main', $data);
        } else {
            show_error('You must have administrator permission.');
        }
    }

    /*
     * Adding a new yonetici
     */
    function add()
    {
        if ($this->yetki < 3) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('kul_adi', 'User Name', 'required|is_unique[yonetici.kul_adi]');
            $this->form_validation->set_rules('kul_pass', 'User Password', 'required');
            $this->form_validation->set_rules('kul_email', 'User Email', 'required|is_unique[yonetici.kul_email]');

            if ($this->form_validation->run()) {
                $params = array(
                    'onay' => $this->input->post('onay'),
                    'kul_adi' => $this->input->post('kul_adi'),
                    'kul_pass' => $this->input->post('kul_pass'),
                    'yetki' => $this->input->post('yetki'),
                    'y_okul_id' => $this->input->post('y_okul_id'),
                    'yetkili' => $this->input->post('yetkili'),
                    'kul_email' => $this->input->post('kul_email'),
                );

                $yonetici_id = $this->Yonetici_model->add_yonetici($params);
                if($yonetici_id>0)
                {
                    $this->send_email($this->input->post('yetkili'), $this->input->post('kul_adi'), $this->input->post('kul_pass'), $this->input->post('kul_email'), "add");
                }
                redirect('yonetici/index');
            } else {
                $this->load->model('Durumlar_model');
                $data['all_durumlar'] = $this->Durumlar_model->get_all_durumlar();

                $this->load->model('Acenta_model');
                $data['all_acenta'] = $this->Acenta_model->get_all_acenta();

                $data['_view'] = 'yonetici/add';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('You must have administrator permission.');
        }
    }

    /*
     * Editing a yonetici
     */
    function edit($y_id)
    {
        // check if the yonetici exists before trying to edit it
        $data['yonetici'] = $this->Yonetici_model->get_yonetici($y_id);
        if ($this->yetki < 3) {
            if (isset($data['yonetici']['y_id'])) {
                $this->load->library('form_validation');

                $this->form_validation->set_rules('kul_adi', 'User Name', 'required');
                $this->form_validation->set_rules('kul_pass', 'User Password', 'required');
                $this->form_validation->set_rules('kul_email', 'User Email', 'required');

                if ($this->form_validation->run()) {
                    $params = array(
                        'onay' => $this->input->post('onay'),
                        'kul_adi' => $this->input->post('kul_adi'),
                        'kul_pass' => $this->input->post('kul_pass'),
                        'yetki' => $this->input->post('yetki'),
                        'y_okul_id' => $this->input->post('y_okul_id'),
                        'yetkili' => $this->input->post('yetkili'),
                        'kul_email' => $this->input->post('kul_email'),


                    );

                    $this->Yonetici_model->update_yonetici($y_id, $params);
                    $this->send_email($this->input->post('yetkili'), $this->input->post('kul_adi'), $this->input->post('kul_pass'), $this->input->post('kul_email'), "update");
                    redirect('yonetici/index');
                } else {
                    $this->load->model('Durumlar_model');
                    $data['all_durumlar'] = $this->Durumlar_model->get_all_durumlar();

                    $this->load->model('Acenta_model');
                    $data['all_acenta'] = $this->Acenta_model->get_all_acenta();

                    $data['_view'] = 'yonetici/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else {
                show_error('The user you are trying to edit does not exist.');
            }
        } else {
            show_error('You must have administrator permission.');
        }
    }

    function send_email($alici_adi_soyadi, $username, $passwordplain, $email, $islem )
    {
        $mail_message = 'Dear ' . $alici_adi_soyadi . ',' . "\r\n";
        if($islem == "add")
        {
            $mail_message .= 'Thanks for contacting regarding to add your account,<br> Your <b>User Name</b> is  <b>' . $username . '</b> and <b>Password</b> is <b>' . $passwordplain . '</b>' . "\r\n";
            $mail_message .= '<br>Please Update your password.';
            $mail_message .= '<br>Thanks & Regards';
            $mail_message .= '<br>Siirt University - International Students Office';

        }
        if($islem == "update")
        {
            $mail_message .= 'Thanks for contacting regarding to update your account,<br> Your <b>User Name</b> is  <b>' . $username . '</b> and <b>Password</b> is <b>' . $passwordplain . '</b>' . "\r\n";
            $mail_message .= '<br>Please Update your password.';
            $mail_message .= '<br>Thanks & Regards';
            $mail_message .= '<br>Siirt University - International Students Office';

        }

        $this->load->library('email');
        $config = array();
        $config['protocol'] = 'smtp';
        $config['smtp_host'] = 'ssl://smtp.gmail.com';
        $config['smtp_user'] = 'agent@siirt.edu.tr';
        $config['smtp_pass'] = 'qazwsx';
        $config['smtp_port'] = 465;
        $config['charset'] = 'utf-8';
        $this->email->initialize($config);
        $this->email->set_mailtype("html");
        $this->email->set_newline("\r\n");

        $from_email = "agent@siirt.edu.tr";
        $to_email = $email;

        $this->email->from($from_email, 'Siirt University');
        $this->email->to($to_email);
        $this->email->subject('Siirt University - International Students Office');
        $this->email->message($mail_message);
        if (!$this->email->send()) {
            $this->session->set_flashdata('msg', 'Failed to send password, please try again!');
        } else {
            $this->session->set_flashdata('msg', 'Password sent to your email!');
        }
    }
}
