<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acenta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
		
    }
    
    /*
     * Get acenta by acenta_id
     */
    function get_acenta($acenta_id)
    {
        return $this->db->get_where('acenta',array('acenta_id'=>$acenta_id))->row_array();
    }
    
    /*
     * Get all acenta count
     */
    function get_all_acenta_count()
    {
        $this->db->from('acenta');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all acenta
     */
    function get_all_acenta($params = array())
    {
        $this->db->order_by('acenta_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('acenta')->result_array();
    }
        
    /*
     * function to add new acenta
     */
    function add_acenta($params)
    {
        $this->db->insert('acenta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update acenta
     */
    function update_acenta($acenta_id,$params)
    {
        $this->db->where('acenta_id',$acenta_id);
        return $this->db->update('acenta',$params);
    }
    
    /*
     * function to delete acenta
     */
    function delete_acenta($acenta_id)
    {
        return $this->db->delete('acenta',array('acenta_id'=>$acenta_id));
    }
}
