<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Basvuru_surec_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get basvuru_surec by surec_id
     */
    function get_basvuru_surec($surec_id)
    {
        return $this->db->get_where('basvuru_surec',array('surec_id'=>$surec_id))->row_array();
    }
        
    /*
     * Get all basvuru_surec
     */
    function get_all_basvuru_surec()
    {
        $this->db->order_by('surec_id', 'desc');
        return $this->db->get('basvuru_surec')->result_array();
    }
        
    /*
     * function to add new basvuru_surec
     */
    function add_basvuru_surec($params)
    {
        $this->db->insert('basvuru_surec',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update basvuru_surec
     */
    function update_basvuru_surec($surec_id,$params)
    {
        $this->db->where('surec_id',$surec_id);
        return $this->db->update('basvuru_surec',$params);
    }
    
    /*
     * function to delete basvuru_surec
     */
    function delete_basvuru_surec($surec_id)
    {
        return $this->db->delete('basvuru_surec',array('surec_id'=>$surec_id));
    }
}
