<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bolum_durumlari_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bolum_durumlari by bolum_durumlari_id
     */
    function get_bolum_durumlari($bolum_durumlari_id)
    {
        return $this->db->get_where('bolum_durumlari',array('bolum_durumlari_id'=>$bolum_durumlari_id))->row_array();
    }
        
    /*
     * Get all bolum_durumlari
     */
    function get_all_bolum_durumlari()
    {
        $this->db->order_by('bolum_durumlari_id', 'desc');
        return $this->db->get('bolum_durumlari')->result_array();
    }
        
    /*
     * function to add new bolum_durumlari
     */
    function add_bolum_durumlari($params)
    {
        $this->db->insert('bolum_durumlari',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bolum_durumlari
     */
    function update_bolum_durumlari($bolum_durumlari_id,$params)
    {
        $this->db->where('bolum_durumlari_id',$bolum_durumlari_id);
        return $this->db->update('bolum_durumlari',$params);
    }
    
    /*
     * function to delete bolum_durumlari
     */
    function delete_bolum_durumlari($bolum_durumlari_id)
    {
        return $this->db->delete('bolum_durumlari',array('bolum_durumlari_id'=>$bolum_durumlari_id));
    }
}
