<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Durumlar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get durumlar by durum_id
     */
    function get_durumlar($durum_id)
    {
        return $this->db->get_where('durumlar',array('durum_id'=>$durum_id))->row_array();
    }
        
    /*
     * Get all durumlar
     */
    function get_all_durumlar()
    {
        $this->db->order_by('durum_id', 'desc');
        return $this->db->get('durumlar')->result_array();
    }
        
    /*
     * function to add new durumlar
     */
    function add_durumlar($params)
    {
        $this->db->insert('durumlar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update durumlar
     */
    function update_durumlar($durum_id,$params)
    {
        $this->db->where('durum_id',$durum_id);
        return $this->db->update('durumlar',$params);
    }
    
    /*
     * function to delete durumlar
     */
    function delete_durumlar($durum_id)
    {
        return $this->db->delete('durumlar',array('durum_id'=>$durum_id));
    }
}
