<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Evraklar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get evraklar by evrak_id
     */
    function get_evraklar($evrak_id)
    {
        return $this->db->get_where('evraklar',array('evrak_id'=>$evrak_id))->row_array();
    }
        
    /*
     * Get all evraklar
     */
    function get_all_evraklar()
    {
        $this->db->order_by('evrak_id', 'desc');
        return $this->db->get('evraklar')->result_array();
    }
       
	       /*
     * Get all evraklar by id
     */
    function get_ogrenci_evraklar($ogrenci_id)
    {
        $this->db->order_by('evrak_id', 'desc');
		$this->db->where('o_id' , $ogrenci_id);
        return $this->db->get('evraklar')->result_array();
    }
        
    /*
     * function to add new evraklar
     */
    function add_evraklar($params)
    {
        $this->db->insert('evraklar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update evraklar
     */
    function update_evraklar($evrak_id,$params)
    {
        $this->db->where('evrak_id',$evrak_id);
        return $this->db->update('evraklar',$params);
    }
    
    /*
     * function to delete evraklar
     */
    function delete_evraklar($evrak_id)
    {
        return $this->db->delete('evraklar',array('evrak_id'=>$evrak_id));
    }
}
