<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fakulte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fakulte by fakulte_id
     */
    function get_fakulte($fakulte_id)
    {
        return $this->db->get_where('fakulte',array('fakulte_id'=>$fakulte_id))->row_array();
    }
        
    /*
     * Get all fakulte
     */
    function get_all_fakulte()
    {
        $this->db->order_by('fakulte_id', 'desc');
        return $this->db->get('fakulte')->result_array();
    }
        
    /*
     * function to add new fakulte
     */
    function add_fakulte($params)
    {
        $this->db->insert('fakulte',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fakulte
     */
    function update_fakulte($fakulte_id,$params)
    {
        $this->db->where('fakulte_id',$fakulte_id);
        return $this->db->update('fakulte',$params);
    }
    
    /*
     * function to delete fakulte
     */
    function delete_fakulte($fakulte_id)
    {
        return $this->db->delete('fakulte',array('fakulte_id'=>$fakulte_id));
    }
}
