<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kabul_mektubu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kabul_mektubu by kabul_id
     */
    function get_kabul_mektubu($kabul_id)
    {
        return $this->db->get_where('kabul_mektubu',array('kabul_id'=>$kabul_id))->row_array();
    }
        
    /*
     * Get all kabul_mektubu
     */
    function get_all_kabul_mektubu()
    {
        $this->db->order_by('kabul_id', 'desc');
        return $this->db->get('kabul_mektubu')->result_array();
    }
        
    /*
     * function to add new kabul_mektubu
     */
    function add_kabul_mektubu($params)
    {
        $this->db->insert('kabul_mektubu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kabul_mektubu
     */
    function update_kabul_mektubu($kabul_id,$params)
    {
        $this->db->where('kabul_id',$kabul_id);
        return $this->db->update('kabul_mektubu',$params);
    }
    
    /*
     * function to delete kabul_mektubu
     */
    function delete_kabul_mektubu($kabul_id)
    {
        return $this->db->delete('kabul_mektubu',array('kabul_id'=>$kabul_id));
    }
}
