<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ogrenci_secimi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ogrenci_secimi by id
     */
    function get_ogrenci_secimi($id)
    {
        return $this->db->get_where('ogrenci_secimi',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all ogrenci_secimi
     */
    function get_all_ogrenci_secimi()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('ogrenci_secimi')->result_array();
    }
        
    /*
     * function to add new ogrenci_secimi
     */
    function add_ogrenci_secimi($params)
    {
        $this->db->insert('ogrenci_secimi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ogrenci_secimi
     */
    function update_ogrenci_secimi($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ogrenci_secimi',$params);
    }
    
    /*
     * function to delete ogrenci_secimi
     */
    function delete_ogrenci_secimi($id)
    {
        return $this->db->delete('ogrenci_secimi',array('id'=>$id));
    }
}
