<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ogrenci_durum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ogrenci_durum by oogrenci_durum_id
     */
    function get_ogrenci_durum($oogrenci_durum_id)
    {
        return $this->db->get_where('ogrenci_durum',array('oogrenci_durum_id'=>$oogrenci_durum_id))->row_array();
    }
    
    /*
     * Get all ogrenci_durum count
     */
    function get_all_ogrenci_durum_count()
    {
        $this->db->from('ogrenci_durum');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ogrenci_durum
     */
    function get_all_ogrenci_durum($params = array())
    {
        $this->db->order_by('oogrenci_durum_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ogrenci_durum')->result_array();
    }
        
    /*
     * function to add new ogrenci_durum
     */
    function add_ogrenci_durum($params)
    {
        $this->db->insert('ogrenci_durum',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ogrenci_durum
     */
    function update_ogrenci_durum($oogrenci_durum_id,$params)
    {
        $this->db->where('oogrenci_durum_id',$oogrenci_durum_id);
        return $this->db->update('ogrenci_durum',$params);
    }
    
    /*
     * function to delete ogrenci_durum
     */
    function delete_ogrenci_durum($oogrenci_durum_id)
    {
        return $this->db->delete('ogrenci_durum',array('oogrenci_durum_id'=>$oogrenci_durum_id));
    }
}
