<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programlar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get programlar by program_id
     */
    function get_programlar($program_id)
    {
        return $this->db->get_where('programlar',array('program_id'=>$program_id))->row_array();
    }
    
    /*
     * Get all programlar count
     */
    function get_all_programlar_count()
    {
        $this->db->from('programlar');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all programlar
     */
    function get_all_programlar($params = array())
    {
        $this->db->order_by('program_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('programlar')->result_array();
    }
        
    /*
     * function to add new programlar
     */
    function add_programlar($params)
    {
        $this->db->insert('programlar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update programlar
     */
    function update_programlar($program_id,$params)
    {
        $this->db->where('program_id',$program_id);
        return $this->db->update('programlar',$params);
    }
    
    /*
     * function to delete programlar
     */
    function delete_programlar($program_id)
    {
        return $this->db->delete('programlar',array('program_id'=>$program_id));
    }
}
