<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ulkeler_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ulkeler by ulke_id
     */
    function get_ulkeler($ulke_id)
    {
        return $this->db->get_where('ulkeler',array('ulke_id'=>$ulke_id))->row_array();
    }
    
    /*
     * Get all ulkeler count
     */
    function get_all_ulkeler_count()
    {
        $this->db->from('ulkeler');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ulkeler
     */
    function get_all_ulkeler($params = array())
    {
        $this->db->order_by('ulke_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ulkeler')->result_array();
    }
        
    /*
     * function to add new ulkeler
     */
    function add_ulkeler($params)
    {
        $this->db->insert('ulkeler',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ulkeler
     */
    function update_ulkeler($ulke_id,$params)
    {
        $this->db->where('ulke_id',$ulke_id);
        return $this->db->update('ulkeler',$params);
    }
    
    /*
     * function to delete ulkeler
     */
    function delete_ulkeler($ulke_id)
    {
        return $this->db->delete('ulkeler',array('ulke_id'=>$ulke_id));
    }
}
