<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Yonetici_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get yonetici by y_id
     */
    function get_yonetici($y_id)
    {
        return $this->db->get_where('yonetici',array('y_id'=>$y_id))->row_array();
    }
    
    /*
     * Get all yonetici count
     */
    function get_all_yonetici_count()
    {
        $this->db->from('yonetici');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all yonetici
     */
    function get_all_yonetici($params = array())
    {
        $this->db->order_by('y_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('yonetici')->result_array();
    }
  /* get all durumlar */
      function get_all_durumlar($params)
    {
        $this->db->order_by('durum_id', 'desc');
		$this->db->where('durum_id' , $params);
        return $this->db->get('durumlar')->result_array();
    }
	      
    /*
     * function to add new yonetici
     */
    function add_yonetici($params)
    {
        $this->db->insert('yonetici',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update yonetici
     */
    function update_yonetici($y_id,$params)
    {
        $this->db->where('y_id',$y_id);
        return $this->db->update('yonetici',$params);
    }
    
    /*
     * function to delete yonetici
     */
    function delete_yonetici($y_id)
    {
        return $this->db->delete('yonetici',array('y_id'=>$y_id));
    }
}
